import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {dirname,resolve} from 'node:path';
import {createServer,request} from 'node:http';
import {app,fields} from '../src/server.mjs';
const listen=s=>new Promise(r=>s.listen(0,'127.0.0.1',()=>r(`http://127.0.0.1:${s.address().port}`)));
const close=s=>new Promise(r=>{s.close(r);s.closeAllConnections();});
const canonical=()=>readFile(new URL('../.runtime/incidents.json',import.meta.url));
test('actual HTTP: canonical data, literal filters, stable sorts, full summaries, details and CSV',async()=>{
 const before=await canonical();const rows=JSON.parse(before);const server=await app();const url=await listen(server);
 try{
 const get=async p=>{const r=await fetch(url+'/api/incidents?'+p);assert.equal(r.status,200);return r.json();};
 const base=await get('');assert.equal(base.total,2400);assert.equal(base.rows.length,25);assert.equal(base.pages,96);
 const rank={critical:0,high:1,medium:2,low:3};
 for(const sort of ['openedAt','severity'])for(const direction of ['asc','desc']){
 const expected=[...rows].sort((a,b)=>{const v=sort==='severity'?rank[a.severity]-rank[b.severity]:a.openedAt.localeCompare(b.openedAt);return v*(direction==='asc'?1:-1)*(sort==='severity'?-1:1)||a.id.localeCompare(b.id);});
 const data=await get(`sort=${sort}&direction=${direction}&size=50`);assert.deepEqual(data.rows,expected.slice(0,50));assert.deepEqual(await get(`sort=${sort}&direction=${direction}&size=50`),data);
 }
 for(const query of ['service=Billing&service=Accounts&status=open&status=in_progress&severity=high&from=2026-04-01&to=2026-04-30','q=RETRY%2C','q=%3Csample%3E','q=INC-000001','q=%5B','from=2026-04-01&to=2026-04-01']){
 const p=new URLSearchParams(query);const expected=rows.filter(r=>[r.id,r.title,r.description].some(v=>v.toLowerCase().includes((p.get('q')||'').toLowerCase()))&&['service','status','severity'].every(k=>!p.has(k)||p.getAll(k).includes(r[k]))&&(!p.has('from')||r.openedAt.slice(0,10)>=p.get('from'))&&(!p.has('to')||r.openedAt.slice(0,10)<=p.get('to')));
 const data=await get(query);assert.equal(data.total,expected.length);assert.equal(data.unresolved,expected.filter(r=>r.status!=='resolved').length);assert.equal(data.high,expected.filter(r=>rank[r.severity]<2).length);const days={};for(const r of expected)days[r.openedAt.slice(0,10)]=(days[r.openedAt.slice(0,10)]||0)+1;assert.deepEqual(data.days,Object.entries(days).sort());
 }
 assert.equal((await get('page=999')).page,96);assert.equal((await get('page=-20')).page,1);assert.equal((await get('page=96')).rows.length,25);
 assert.deepEqual(await (await fetch(url+'/api/incidents/INC-000001')).json(),rows[0]);
 const csv=await(await fetch(url+'/api/export?sort=openedAt&direction=asc')).text();
 // Parse quoted RFC-style CSV, including embedded CR/LF, commas and doubled quotes.
 const parsed=[];let row=[],cell='',quoted=false;for(let i=0;i<csv.length;i++){const c=csv[i];if(c==='"'){if(quoted&&csv[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if(c==='\r'&&!quoted&&csv[i+1]==='\n'){row.push(cell);parsed.push(row);row=[];cell='';i++;}else cell+=c;}row.push(cell);parsed.push(row);
 assert.deepEqual(parsed[0],fields);assert.equal(parsed.length,2401);const ordered=[...rows].sort((a,b)=>a.openedAt.localeCompare(b.openedAt)||a.id.localeCompare(b.id));assert.deepEqual(parsed.slice(1),ordered.map(r=>fields.map(k=>Array.isArray(r[k])?JSON.stringify(r[k]):String(r[k]??''))));
 }finally{await close(server);assert.deepEqual(await canonical(),before);assert.equal(createHash('sha256').update(before).digest('hex'),'c961927b45ee0205608382d14b481a5e3761c51304b3de09c7e5cc18a2f466ac');}
});
test('real sandboxed browser: journeys, actual delayed HTTP and network failures',async()=>{
 const alias=dirname(execFileSync('bash',['-c','command -v qualification-chromium'],{encoding:'utf8'}).trim());process.env.PLAYWRIGHT_BROWSERS_PATH=resolve(alias,'../browsers');await mkdir('.runtime/browser-tmp',{recursive:true});
 const {chromium}=await import('playwright');const backend=await app();const upstream=await listen(backend);
 let delay=()=>0,fail=()=>false;const pending=new Set();
 // Forward genuine backend responses unchanged; delay delivery or close an actual connection.
 const proxy=createServer((req,res)=>{const wait=delay(req.url),broken=fail(req.url);const p=request(upstream+req.url,{method:req.method},r=>{const chunks=[];r.on('data',c=>chunks.push(c));r.on('end',()=>{const timer=setTimeout(()=>{pending.delete(timer);if(broken){res.destroy();return;}res.writeHead(r.statusCode,r.headers);res.end(Buffer.concat(chunks));},wait);pending.add(timer);});});p.on('error',()=>res.destroy());p.end();});const url=await listen(proxy);let browser;
 try{
 browser=await chromium.launch({channel:'chromium',headless:true,chromiumSandbox:true,env:{...process.env,LD_LIBRARY_PATH:resolve(alias,'../host-libs/usr/lib/x86_64-linux-gnu'),ALSA_CONFIG_PATH:resolve(alias,'../host-libs/usr/share/alsa/alsa.conf'),TMPDIR:'.runtime/browser-tmp',TMP:'.runtime/browser-tmp',TEMP:'.runtime/browser-tmp'}});
 const page=await browser.newPage();await page.goto(url);const status=page.locator('#status');const ready=()=>page.waitForFunction(()=>document.querySelector('#status').textContent.includes('matching incidents'));
 await ready();assert.equal(await page.locator('#rows tr').count(),25);assert.equal(await page.locator('#counts strong').first().textContent(),'2400');
 await page.getByLabel('Search incidents').focus();await page.keyboard.type('INC-000001');await ready();assert.equal(await page.locator('#rows tr').count(),1);assert.ok(await page.locator('#q').evaluate(e=>getComputedStyle(e).outlineStyle!=='none'));
 await page.getByRole('button',{name:'INC-000001'}).click();await page.waitForFunction(()=>document.querySelector('#detailBody dt')!==null);assert.equal(await page.locator('#detailBody dt').count(),11);await page.getByRole('button',{name:'Back to results'}).click();assert.equal(await page.locator('#q').inputValue(),'INC-000001');
 await page.getByRole('button',{name:'Clear selections'}).click();await ready();await page.getByLabel('Rows per page').selectOption('50');await ready();assert.equal(await page.locator('#rows tr').count(),50);
 await page.getByLabel('Billing',{exact:true}).check();await ready();await page.getByLabel('Sort',{exact:true}).selectOption('severity');await page.getByLabel('Direction').selectOption('asc');await page.getByLabel('Opened from').fill('2026-04-01');await page.getByLabel('Opened through').fill('2026-04-30');await ready();await page.getByLabel('Search incidents').fill('response');await page.getByLabel('high',{exact:true}).check();await page.getByLabel('open',{exact:true}).check();await ready();await page.getByLabel('View name').fill('April billing');await page.getByRole('button',{name:'Save view'}).click();await page.reload();await ready();await page.getByLabel('Saved views').selectOption('April billing');await page.getByRole('button',{name:'Open view'}).click();await ready();assert.equal(await page.getByLabel('Rows per page').inputValue(),'50');assert.equal(await page.getByLabel('Direction').inputValue(),'asc');assert.equal(await page.getByLabel('Opened through').inputValue(),'2026-04-30');assert.ok(await page.getByLabel('Billing',{exact:true}).isChecked());assert.ok(await page.getByLabel('high',{exact:true}).isChecked());assert.ok(await page.getByLabel('open',{exact:true}).isChecked());assert.equal(await page.locator('#q').inputValue(),'response');assert.equal(await page.locator('#sort').inputValue(),'severity');assert.equal(await page.locator('#from').inputValue(),'2026-04-01');await page.getByRole('button',{name:'Delete view'}).click();assert.equal(await page.locator('#views option').count(),1);
 await page.locator('summary').click();assert.ok(await page.locator('#chart').textContent());const savedExpected=await(await fetch(upstream+'/api/incidents?'+await page.evaluate(()=>new URL(document.querySelector('#export').href).search.slice(1)))).json();assert.equal(await page.locator('#counts strong').first().textContent(),String(savedExpected.total));
 await page.getByRole('button',{name:'Clear selections'}).click();await ready();for(let i=0;i<12;i++)await page.locator('#next').click();await ready();assert.ok(Number((await page.locator('#page').textContent()).match(/Page (\d+)/)[1])<=96);await page.locator('#prev').focus();await page.keyboard.press('Enter');await ready();
 // Only two pages: repeated pointer and keyboard actions while requests are pending stay bounded.
 await page.locator('#q').fill('Scenario 1.');await ready();delay=u=>u.startsWith('/api/incidents?')?150:0;for(let i=0;i<8;i++){await page.locator('#next').focus();await page.keyboard.press('Enter');}await ready();assert.equal(await page.locator('#page').textContent(),'Page 1 of 1');await page.locator('#q').fill('retry, then continue');await ready();for(let i=0;i<8;i++){await page.locator('#next').focus();await page.keyboard.press('Enter');}await ready();assert.equal(await page.locator('#page').textContent(),'Page 3 of 3');assert.ok(await page.locator('#next').isDisabled());for(let i=0;i<8;i++){await page.locator('#prev').focus();await page.keyboard.press('Enter');}await ready();assert.equal(await page.locator('#page').textContent(),'Page 1 of 3');delay=()=>0;
 await page.getByLabel('Search incidents').fill('no such incident');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('No incidents'));assert.equal(await page.locator('#rows tr').count(),0);
 delay=u=>u.includes('q=slow')?300:0;await page.locator('#q').fill('slow');await page.locator('#q').fill('INC-000002');await ready();await page.waitForTimeout(400);assert.equal(await page.locator('#rows button').first().textContent().then(s=>s.slice(0,10)),'INC-000002');
 fail=u=>u.includes('q=slow');await page.locator('#q').fill('slow');await page.locator('#q').fill('INC-000003');await ready();await page.waitForTimeout(400);assert.ok((await status.textContent()).includes('matching'));assert.ok(await page.locator('#retry').isHidden());assert.equal(await page.locator('#counts strong').first().textContent(),'1');assert.equal(await page.locator('#chart .day').count(),1);
 fail=u=>u.startsWith('/api/incidents?');await page.locator('#q').fill('INC-000004');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Could not load'));assert.equal(await page.locator('#q').inputValue(),'INC-000004');fail=()=>false;await page.getByRole('button',{name:'Retry'}).click();await ready();assert.ok((await page.locator('#rows').textContent()).includes('INC-000004'));
 delay=u=>u.startsWith('/api/incidents/INC-000004')?300:0;await page.locator('#rows button').click();await page.locator('#back').click();await page.waitForTimeout(400);assert.ok(await page.locator('#detail').isHidden());assert.ok(await page.locator('#results').isVisible());
 // Replace a pending detail intent through a real selection change, then open its replacement.
 await page.locator('#rows button').click();await page.locator('#q').fill('INC-000005');await ready();await page.locator('#rows button').click();await page.waitForFunction(()=>document.querySelector('#detailBody').textContent.includes('INC-000005'));await page.waitForTimeout(400);assert.ok(!(await page.locator('#detailBody').textContent()).includes('INC-000004'));
 await page.locator('#back').click();fail=u=>u.includes('/api/incidents/INC-000005');delay=u=>u.includes('/api/incidents/INC-000005')?300:0;await page.locator('#rows button').click();await page.locator('#q').fill('INC-000006');await ready();await page.locator('#rows button').click();await page.waitForFunction(()=>document.querySelector('#detailBody').textContent.includes('INC-000006'));await page.waitForTimeout(400);assert.ok(await page.locator('#retry').isHidden());assert.ok((await status.textContent()).includes('INC-000006'));
 await page.locator('#back').click();
 fail=u=>u.includes('/api/incidents/INC-000006');delay=()=>0;await page.locator('#rows button').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Could not load details'));fail=()=>false;await page.locator('#retry').click();await page.waitForFunction(()=>document.querySelector('#detailBody').textContent.includes('INC-000006'));await page.locator('#back').click();
 fail=u=>u.includes('/api/incidents/INC-000006');delay=u=>u.includes('/api/incidents/INC-000006')?250:0;await page.locator('#rows button').click();await page.locator('#back').click();await page.waitForTimeout(350);assert.ok(await page.locator('#detail').isHidden());assert.ok(await page.locator('#retry').isHidden());fail=()=>false;delay=()=>0;
 const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'incidents.csv');await download.saveAs('.runtime/browser-export.csv');assert.ok((await readFile('.runtime/browser-export.csv','utf8')).includes('INC-000006'));
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Clear selections'}).click();await ready();assert.ok(await page.locator('#q').isVisible());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 delay=u=>u.startsWith('/api/incidents?')?250:0;await page.locator('#q').fill('retry');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Loading'));await ready();await page.screenshot({path:'.runtime/explorer-mobile.png',fullPage:true});
 }finally{await browser?.close();for(const timer of pending)clearTimeout(timer);await close(proxy);await close(backend);}
});
